[package]
name = "binary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-chef = { path = "../cargo-chef", version = "1.0" }
cargo-chef-legacy = { package = "cargo-chef", version = "0.1.61" }
